# Grafana Datasource Auto-Provisioning
# InfluxDB 2.x 자동 설정

apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ky661
      defaultBucket: ky661
      tlsSkipVerify: true
    secureJsonData:
      token: slam_mqtt_token_2024
    isDefault: true
    editable: true
